/**
 * useWasmEngine — loads the Rust-WASM computation engine (`iort-twin-wasm`)
 * and exposes a typed, honest API surface.
 *
 * Honesty contract: when WASM is unavailable (unsupported browser, load
 * failure), the hook reports `ready: false` and the UI must fall back to its
 * JS mirror — the operator always sees working numbers, plus a "fallback"
 * badge. We never silently degrade.
 *
 * The wasm module is a static public asset (mission-control/public/wasm/),
 * generated by `wasm-bindgen --target web`. Vite serves it at /wasm/.
 */
import { useEffect, useState } from "react";

/** Typed surface matching the generated iort_twin_wasm.d.ts (subset used here). */
export interface CusumDetectorLike {
  update(z: number): CusumAlertLike | undefined;
  reset(): void;
  readonly s_plus: number;
  readonly s_minus: number;
  readonly threshold_h: number;
  readonly reference_k: number;
  readonly samples: number;
  readonly alarms: number;
}
export interface CusumAlertLike {
  readonly direction: number;
  readonly direction_label: string;
  readonly s_plus: number;
  readonly s_minus: number;
}
export interface DecodedStateLike {
  readonly auv_id: number;
  readonly timestamp: number;
  readonly sequence: number;
  readonly x_m: number;
  readonly y_m: number;
  readonly z_m: number;
  readonly battery_v: number;
  readonly crc_ok: boolean;
  readonly anomaly_detected: boolean;
  readonly mission_phase: number;
}
export interface PnrResultLike {
  readonly minutes_to_pnr: number;
  readonly return_time_min: number;
  readonly energy_required_wh: number;
  readonly battery_required_pct: number;
  readonly can_safely_return: boolean;
}

interface WasmModule {
  default(): Promise<unknown>;
  engine_version(): string;
  new_cusum_detector(): CusumDetectorLike;
  decode_state_vector(bytes: Uint8Array): DecodedStateLike | undefined;
  crc16_ccitt_false(data: Uint8Array): number;
  pnr_minutes(
    battery_pct: number,
    capacity_wh: number,
    distance_m: number,
    speed_ms: number,
    power_w: number,
    margin: number
  ): PnrResultLike;
}

export interface WasmEngineState {
  ready: boolean;
  version: string | null;
  error: string | null;
  /** Creates a CUSUM detector preconfigured with production h=10.5, k=0.5. */
  newCusumDetector: (() => CusumDetectorLike) | null;
  decodeStateVector: ((bytes: Uint8Array) => DecodedStateLike | undefined) | null;
  crc16: ((data: Uint8Array) => number) | null;
  pnrMinutes: ((
    batteryPct: number,
    capacityWh: number,
    distanceM: number,
    speedMs: number,
    powerW: number,
    margin: number
  ) => PnrResultLike) | null;
}

const IDLE: WasmEngineState = {
  ready: false,
  version: null,
  error: null,
  newCusumDetector: null,
  decodeStateVector: null,
  crc16: null,
  pnrMinutes: null,
};

export function useWasmEngine(): WasmEngineState {
  const [state, setState] = useState<WasmEngineState>(IDLE);

  useEffect(() => {
    let cancelled = false;

    (async () => {
      try {
        // Static public asset — @vite-ignore keeps Vite from bundling it, and a
        // variable specifier keeps TS from resolving it (typed via the local
        // WasmModule interface below).
        const wasmUrl = "/wasm/iort_twin_wasm.js";
        const mod = (await import(/* @vite-ignore */ wasmUrl)) as WasmModule;
        await mod.default();
        if (cancelled) return;
        setState({
          ready: true,
          version: mod.engine_version(),
          error: null,
          newCusumDetector: () => mod.new_cusum_detector(),
          decodeStateVector: (bytes) => mod.decode_state_vector(bytes),
          crc16: (data) => mod.crc16_ccitt_false(data),
          pnrMinutes: (b, c, d, s, p, m) => mod.pnr_minutes(b, c, d, s, p, m),
        });
      } catch (err) {
        if (cancelled) return;
        setState({
          ...IDLE,
          error: err instanceof Error ? err.message : String(err),
        });
      }
    })();

    return () => {
      cancelled = true;
    };
  }, []);

  return state;
}
